# Site settings
title: 折腾志
email: xzturn@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Keep Beginner's Mind.
  Stay hungry, Stay Foolish.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://xzturn.com" # the base hostname & protocol for your site
twitter_username: sunpeng
github_username:  xzturn

# Build settings
markdown: kramdown
