# Site settings
title: XZturn's Blog
email: peng.sunshine@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Zen, Beginner's Mind.
baseurl: "/display" # the subpath of your site, e.g. /blog/
url: "http://xzturn.com" # the base hostname & protocol for your site
twitter_username: sunpeng
github_username:  xzturn

# Build settings
markdown: kramdown
